services:
  frontend:
    build: ./frontend
    container_name: bazar-frontend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CATALOG_REPLICAS: http://catalog:3001,http://catalog-replica:3003
      ORDER_REPLICAS: http://order:3002,http://order-replica:3004
    depends_on:
      - catalog
      - catalog-replica
      - order
      - order-replica
    networks:
      - bazar-network

  catalog:
    build: ./catalog
    container_name: bazar-catalog
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      REPLICA_URL: http://catalog-replica:3003
      FRONTEND_URL: http://frontend:3000
    volumes:
      - ./catalog/catalog-data.csv:/app/catalog-data.csv
    networks:
      - bazar-network

  catalog-replica:
    build: ./catalog-replica
    container_name: bazar-catalog-replica
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
    volumes:
      - ./catalog-replica/catalog-data.csv:/app/catalog-data.csv
    networks:
      - bazar-network

  order:
    build: ./order
    container_name: bazar-order
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      CATALOG_URL: http://catalog:3001
      REPLICA_URL: http://order-replica:3004
    volumes:
      - ./order/orders-data.csv:/app/orders-data.csv
    depends_on:
      - catalog
    networks:
      - bazar-network

  order-replica:
    build: ./order-replica
    container_name: bazar-order-replica
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      CATALOG_URL: http://catalog:3001
      REPLICA_URL: http://order:3002
    volumes:
      - ./order-replica/orders-data.csv:/app/orders-data.csv
    depends_on:
      - catalog
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge
